<a href="https://colab.research.google.com/github/aqilaqsa/Artificial-Intelligence/blob/main/Soal_Praktikum_Modul_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum Modul 2 AI

- Selamat datang di Praktikum Modul 2, bantu Rendy Atreides dalam menyelesaikan soal soal modul Statistika dan Probabilitas. <br>
- Jika ada pertanyaan silahkan tanyakan di **#use-ask** discord praktikum.

# Table of Contents
- [Case A](#A)
    - [ Soal 1](#1)
- [Case B](#B)
    - [ Soal 2](#2)
- [Case C](#C)
    - [ Soal 3](#3)
- [Case D](#D)
    - [ Soal 4](#4)
    - [ Soal 5](#5)
- [ Soal 6](#6)

In [ ]:
# Tambahkan sendiri seperlunya
import numpy as np
import pandas as pd

from scipy.stats import binom

<a name='A'></a>
## Case A

- Rendy Atreides mempunyai penglihatan terhadap musim hujan yang akan datang, karena hal tersebut ada kemungkinan/probabilitas teman dan kerabat nya untuk mendapatkan flu, $P(\text{flu})$
- Jika orang tersebut mendapatkan **vaksinasi**, maka peluang orang tersebut untuk terjangkit flu **seharusnya** berubah.

- Diberikan data berikut

| Kondisi   | Suhu Rata-rata (°C) | Vaksin | Tidak Vaksin | PDB Regional (dalam Miliar) | Jumlah Hari Libur Nasional | Rata-rata Jam Matahari per Hari |
|-----------|---------------------|--------|--------------|-----------------------------|----------------------------|---------------------------------|
| Flu       | 27                  | 200    | 900          | 650                         | 12                         | 6                               |
| Tidak Flu | 27                  | 4000   | 9000         | 650                         | 12                         | 6                               |




---
<a name='1'></a>
### **Soal 1**:
A. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila telah vaksin? <br>

$$
\begin{align*}
P(\text{flu} \ | \ \text{vaksin}) &= ?
\end{align*}
$$

B. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila **belum** divaksin?

In [ ]:
n_flu_dan_vaksin = 200
n_flu_dan_tidak_vaksin = 900

n_tidak_flu_dan_vaksin = 4000
n_tidak_flu_dan_tidak_vaksin = 9000

### A. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila telah vaksin?

In [ ]:
n_vaksin = n_flu_dan_vaksin + n_tidak_flu_dan_vaksin

print(f"Jumlah orang yang divaksin : {n_vaksin}")

p_flu_jika_vaksin = n_flu_dan_vaksin / n_vaksin

print(f"A. Peluang orang mengalami flu jika sudah vaksin : {p_flu_jika_vaksin:.4f}")

Jumlah orang yang divaksin : 4200
A. Peluang orang mengalami flu jika sudah vaksin : 0.0476


Solver:

$$
\begin{align*}
P(\text{flu} \ | \ \text{vaksin}) &= \cfrac{n(\text{flu} \cap \text{vaksin})}{n(\text{vaksin})}
\end{align*}
$$

### B. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila **belum** divaksin?

In [ ]:
n_tidak_vaksin = n_flu_dan_tidak_vaksin + n_tidak_flu_dan_tidak_vaksin

p_flu_jika_belum_vaksin = n_flu_dan_tidak_vaksin / n_tidak_vaksin
print(f"Peluang orang mengalami flu jika belum vaksin : {p_flu_jika_belum_vaksin:.4f}")

Peluang orang mengalami flu jika belum vaksin : 0.0909


Solver:

$$
\begin{align*}
P(\text{flu} \ | \ \text{tidak vaksin}) &= \cfrac{n(\text{flu} \cap \text{tidak vaksin})}{n(\text{tidak vaksin})}
\end{align*}
$$

**Penjelasan Pengerjaan Soal 1** <br>

Untuk mengerjakan soal Case A di atas, menggunakan rumus probabilitas bersyarat yaitu<br><br>
$$
\begin{align*}
P(\text{A} \ | \ \text{B}) &= \cfrac{P(\text{A} \cap \text{B})}{P(\text{B})}
\end{align*}
$$
<br>
di kasus ini, A adalah pengidap flu dan B adalah antara vaksin atau tidak vaksin. Teori probabilitas bersyarat dalam konteks ini digunakan untuk memahami bagaimana vaksinasi mempengaruhi peluang mengidap flu.

Langkah pengerjaan:
1. karena variabel telah disediakan, hanya perlu memasukkan jumlahnya sesuai dari tabel data yang ada.
2. lalu, untuk menjawab soal **`A. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila telah vaksin?`** , kita hitung terlebih dahulu jumlah total populasi orang yang telah divaksin dan disimpan di `n_vaksin`
3. selanjutnya, hitung probabilitas pengidap flu yang telah divaksin sesuai dengan rumusnya dengan membagi jumlah orang yang mengidap flu dan telah divaksin dibagi dengan total jumlah orang yang telah divaksin.
4. setelah itu, untuk menjawab soal **`B. Dari data di atas, berapa peluang seseorang akan mengidap flu apabila belum divaksin?`** hampir sama dengan A, kita hitung jumlah total populasi orang yang tidak divaksin dan disimpan di `n_tidak_vaksin`
5. selanjutnya, hitung probabilitas pengidap flu yang belum divaksin dihitung dari membagi jumlah orang yang flu dan belum divaksin dengan total jumlah orang yang belum divaksin.

```
Jumlah orang yang divaksin : 4200
A. Peluang orang mengalami flu jika sudah vaksin : 0.0476
B. Peluang orang mengalami flu jika belum vaksin : 0.0909
```

<a name='B'></a>
## Case B = Pengaruh Cuaca Terhadap Frekuensi Penggunaan Transportasi Umum

- Telah diamati bahwa cuaca memiliki pengaruh terhadap keputusan orang menggunakan transportasi umum. Anda memiliki data historis dari perusahaan transportasi umum yang mencatat jumlah penumpang per hari selama berbagai kondisi cuaca.

- Diberikan data berikut

| Data Operasi       | Pengguna ketika Hujan | Pengguna ketika Cerah | Promo yang berlaku | Zona Tarif |
|--------------------|-------|-------|--------------------|------------|
| Grab-bike          | 4     | 475   |Diskon 10%          |Zona 1      |
| Grab-car           | 185   | 49    |Tidak ada promo     |Zona 2      |




---
<a name='2'></a>
### **Soal 2**:
A. Berapa peluang **orang menggunakan produk grab-bike?** <br>
B. Berapa peluang **orang menggunakan produk grab-car** jika diketahui **terjadi hujan**<br>
C. Berapa peluang **orang menggunakan produk grab-car** jika diketahui **hari cerah**<br>
D. Bagaimana konsep probabilitas bersyarat digunakan untuk menghitung peluang penggunaan produk grab-car ketika diketahui kondisi cuaca (hujan atau cerah), dan mengapa ini penting dalam menganalisis data operasi seperti ini?

In [ ]:
n_gbike_dan_hujan = 4
n_gbike_dan_cerah = 475

n_gcar_dan_hujan = 185
n_gcar_dan_cerah = 49

### A. Berapa peluang **orang menggunakan produk grab-bike?**

In [ ]:
n_gbike = n_gbike_dan_hujan + n_gbike_dan_cerah
n_produk = n_gbike_dan_hujan + n_gbike_dan_cerah + n_gcar_dan_hujan + n_gcar_dan_cerah

print(f"Jumlah orang yang menggunakan produk grab : {n_produk}")

soal_2A = n_gbike / n_produk

print(f"2A. Peluang orang menggunakan produk grab-bike adalah : {soal_2A =:.2f}")

Jumlah orang yang menggunakan produk grab : 713
2A. Peluang orang menggunakan produk grab-bike adalah : soal_2A =0.67


Solver:

$$
\begin{align*}
P(\text{grabbike}) &= \cfrac{n(\text{grabbike})}{n(\text{produk})}
\end{align*}
$$

### B. Berapa peluang **orang menggunakan produk grab-car** jika diketahui **terjadi hujan**

In [ ]:
n_hujan = n_gbike_dan_hujan + n_gcar_dan_hujan

Soal_2B = n_gcar_dan_hujan / n_hujan

print(f"2B. Peluang orang menggunakan produk go-car jika diketahui terjadi hujan adalah : {Soal_2B:.2f}")

2B. Peluang orang menggunakan produk go-car jika diketahui terjadi hujan adalah : 0.98


Solver:

$$
\begin{align*}
P(\text{A} \ | \ \text{B}) &= \cfrac{P(\text{A} \cap \text{B})}{P(\text{B})}
\end{align*}
$$
<br>

 $$
\begin{align*}
P(\text{grabcar} \ | \ \text{hujan}) &= \cfrac{n(\text{grabcar} \cap \text{hujan})}{n(\text{hujan})}
\end{align*}
$$

### C. Berapa peluang **orang menggunakan produk grab-car** jika diketahui **hari cerah**

In [ ]:
n_cerah = n_gbike_dan_cerah + n_gcar_dan_cerah

Soal_2C = n_gcar_dan_cerah / n_cerah

print(f"2C. peluang orang menggunakan produk grab-car jika diketahui hari cerah : {Soal_2C:.2f}")

2C. peluang orang menggunakan produk grab-car jika diketahui hari cerah : 0.09


 $$
\begin{align*}
P(\text{grabcar} \ | \ \text{cerah}) &= \cfrac{n(\text{grabcar} \cap \text{cerah})}{n(\text{cerah})}
\end{align*}
$$

### D. Bagaimana konsep probabilitas bersyarat digunakan untuk menghitung peluang penggunaan produk grab-car ketika diketahui kondisi cuaca (hujan atau cerah), dan mengapa ini penting dalam menganalisis data operasi seperti ini?

D. konsep probabilitas bersyarat penting dalam menganalisis situasi seperti penggunaan produk Grab-car berdasarkan kondisi cuaca karena memungkinkan kita untuk memahami bagaimana satu kondisi seperti cuaca dapat mempengaruhi kemungkinan kondisi lain yaitu keputusan untuk menggunakan Grab-car atau Grab-bike. Seperti yang telah diberikan di atas, formula untuk menghitung probabilitas bersyarat yaitu:

$$
\begin{align*}
P(\text{A} \ | \ \text{B}) &= \cfrac{P(\text{A} \cap \text{B})}{P(\text{B})}
\end{align*}
$$
<br>

yang berarti peluang kejadian A jika diketahui kejadian B, dalam konteks ini A misalnya Grab-car dan B adalah cuaca.

data operasi ini penting bagi perusahaan untuk memahami preferensi pengguna dalam kondisi tertentu, mengalokasikan sumber daya dengan tepat sesuai data yang didapat, menerapkan harga sesuai demand, dan lainnya.

**Penjelasan Pengerjaan Soal 2** <br>
untuk pengerjaan soal ini kembali digunakan konsep probabilitas bersyarat, seperti yang telah saya tambahkan rumusnya di atas.
<br><br>
$$
\begin{align*}
P(\text{A} \ | \ \text{B}) &= \cfrac{P(\text{A} \cap \text{B})}{P(\text{B})}
\end{align*}
$$
<br>

di kasus ini, A adalah pengguna grab-bike/grab-car dan B adalah antara cuaca hujan atau cerah. Teori probabilitas bersyarat dalam konteks ini digunakan untuk memahami bagaimana kondisi cuaca mempengaruhi peluang pengguna mengambil keputusan untuk menggunakan layanan grab-bike atau grab-car.

Langkah pengerjaan:
1. buat variabel menggunakan data yang ada:
```
n_gbike_dan_hujan = 4
n_gbike_dan_cerah = 475
n_gcar_dan_hujan = 185
n_gcar_dan_cerah = 49
```
yang akan digunakan untuk perhitungan nanti.
2. lalu, untuk menjawab soal **`A. Berapa peluang orang menggunakan produk grab-bike?`** , kita hitung terlebih dahulu jumlah orang yang menggunakan grab-bike yang disimpan di `n_gbike` dan jumlah total populasi pengguna yang menggunakan kedua layanan kembali menggunakan `n_produk`.
3. selanjutnya, hitung peluang orang menggunakan grab-bike dengan rumus peluang sederhana:
$$
\begin{align*}
P(\text{A}) &= \cfrac{n(\text{A})}{n(\text{B})}
\end{align*}
$$
pada kasus ini, A merupakan pengguna grab-bike di cuaca hujan dan cerah dan B merupakan total pengguna layanan grab.
4. jadi, peluang orang menggunakan produk grab-bike dihitung dari total penggunaan grab-bike dibagi dengan total penggunaan semua produk grab.
```
Peluang Grab-bike = n_gbike / n_produk
```
5. **`B. Berapa peluang orang menggunakan produk grab-car jika diketahui terjadi hujan?`** dihitung menggunakan rumus probabilitas bersyarat seperti yang telah saya tambahkan di atas dengan cara membagi jumlah penggunaan Grab-car saat hujan dengan total jumlah penggunaan grab-bike dan grab-car saat hujan untuk mengetahui peluang menggunakan grab-car dalam kondisi hujan. Di sini, jumlah grab-bike dan grab-car yang digunakan saat hujan disimpan di `n_hujan`.  (*n_hujan = n_gbike_dan_hujan + n_gcar_dan_hujan*)
```
Peluang Grab-car Saat Hujan = n_gcar_dan_hujan / n_hujan
```
6. **`C. Berapa peluang orang menggunakan produk grab-car jika diketahui hari cerah`** dihitung dengan membagi jumlah penggunaan Grab-car saat cerah dengan total kasus cerah untuk mengetahui peluang menggunakan Grab-car dalam kondisi cerah. Di sini, jumlah grab-bike dan grab-car yang digunakan saat cuaca cerah disimpan dalam `n_cerah`. (*n_cerah = n_gbike_dan_cerah + n_gcar_dan_cerah*)
```
Peluang Grab-car Saat Cerah = n_gcar_dan_cerah / n_cerah
```

```
Jumlah orang yang menggunakan produk grab : 713
2A. Peluang orang menggunakan produk grab-bike adalah : soal_2A =0.67
2B. Peluang orang menggunakan produk go-car jika diketahui terjadi hujan adalah : 0.98
2C. peluang orang menggunakan produk grab-car jika diketahui hari cerah : 0.09
```

---
<a name='C'></a>
## **Case 3**: Sebuah perusahaan IT memiliki dua divisi, Divisi Pengembangan dan Divisi Pemasaran, yang keduanya mempekerjakan para profesional IT. Dalam Divisi Pengembangan, 30% dari pekerja memiliki pengalaman kerja kurang dari 3 tahun, sedangkan di Divisi Pemasaran, 70% dari pekerja memiliki pengalaman kerja kurang dari 3 tahun.

<a name='3'></a>
### Soal 3.
A. Jika seorang pekerja dipilih secara acak dan ternyata memiliki pengalaman kerja kurang dari 3 tahun, berapa probabilitas bahwa pekerja tersebut berasal dari Divisi Pengembangan? <br>
B. Dengan mempertimbangkan informasi dari Divisi Pengembangan dan Divisi Pemasaran seperti yang diberikan sebelumnya, jika diketahui bahwa sebuah proyek baru memerlukan tim yang terdiri dari pekerja dengan pengalaman kerja kurang dari 3 tahun, dan satu pekerja dipilih secara acak dari keseluruhan pekerja yang memenuhi kriteria ini, berapa rasio antara probabilitas pekerja tersebut berasal dari Divisi Pengembangan terhadap probabilitas pekerja tersebut berasal dari Divisi Pemasaran?

In [ ]:
P_exp_dev = 0.3  # Probabilitas pengalaman < 3 tahun jika dari divisi pengembangan
P_exp_marketing = 0.7  # Probabilitas pengalaman < 3 tahun jika dari divisi pemasaran
P_dev = 0.5  # Probabilitas memilih seorang pekerja dari divisi pengembangan
P_marketing= 0.5  # Probabilitas memilih seorang pekerja dari divisi pemasaran

### A. Jika seorang pekerja dipilih secara acak dan ternyata memiliki pengalaman kerja kurang dari 3 tahun, berapa probabilitas bahwa pekerja tersebut berasal dari Divisi Pengembangan?

In [ ]:
#rumus: P(dev|exp<3) = (P(exp<3|dev) * P(dev)) / P(exp<3)
P_exp_less_than_3 = P_exp_dev * P_dev + P_exp_marketing * P_marketing
P_dev_with_exp_less_than_3 = (P_exp_dev * P_dev) / P_exp_less_than_3

Soal_3_A = P_dev_with_exp_less_than_3

print(f"3A. Jawaban : {Soal_3_A:.2f}")

3A. Jawaban : 0.30


Solver:
$$
\begin{align*}
P(\text{A} \ | \ \text{B}) &= \cfrac{P(\text{B} | \text{A})\times P(\text{A})}{P(\text{B})}
\end{align*}
$$

<br>

$$
\begin{align*}
P(\text{dev} \ | \ \text{exp < 3}) &= \cfrac{P(\text{exp < 3} | \text{dev})\times P(\text{dev})}{P(\text{exp < 3})}
\end{align*}
$$



### B. Rasio probabilitas pekerja berasal dari Divisi Pengembangan terhadap Divisi Pemasaran

In [ ]:
ratio_dev_to_marketing = (P_exp_dev * P_dev) / (P_exp_marketing * P_marketing)

Soal_3_B = ratio_dev_to_marketing
print(f"3B. Jawaban : {Soal_3_B:.2f}")

3B. Jawaban : 0.43


Solver:
$$
\begin{align*}
\frac{P(\text{dev} | \text{exp} < 3)}{P(\text{marketing} | \text{exp} < 3)}
\end{align*}
$$

<br>

$$
\begin{align*}
P(\text{marketing} | \text{exp}<3) &= \cfrac{P(\text{exp}<3 | \text{marketing}) \times P(\text{marketing})}{P(\text{exp}<3)}
\end{align*}
$$



**Penjelasan Pengerjaan Soal 3** <br>

untuk mengerjakan no 3, saya menggunakan teori Bayes, karena teori ini memberikan cara untuk menghitung probabilitas suatu kejadian dengan mempertimbangkan informasi atau kejadian lain yang telah diketahui terjadi yang sangat relevan untuk kasus ini, di mana kita ingin mengetahui probabilitas  seorang pekerja berasal dari divisi pengembangan diketahui memiliki pengalaman kerja kurang dari 3 tahun. Untuk solver, saya tambahkan di atas.

1. mulai dengan mendefinisikan variabel seperti di atas:
```
P_exp_dev = 0.3  # Probabilitas pengalaman < 3 tahun jika dari divisi pengembangan
P_exp_marketing = 0.7  # Probabilitas pengalaman < 3 tahun jika dari divisi pemasaran
P_dev = 0.5  # Probabilitas memilih seorang pekerja dari divisi pengembangan
P_marketing= 0.5  # Probabilitas memilih seorang pekerja dari divisi pemasaran
```
2. lalu, menentukan probabilitas total pengalaman kerja kurang dari 3 tahun: `P_exp_less_than_3 = P_exp_dev * P_dev + P_exp_marketing * P_marketing`
3. selanjutnya, menghitung probabilitas pekerja dari divisi pengembangan diketahui memiliki pengalaman kerja kurang dari 3 tahun: `P_dev_with_exp_less_than_3 = (P_exp_dev * P_dev) / P_exp_less_than_3`
4. untuk soal B, hitung rasio antara probabilitas pekerja berasal dari Divisi Pengembangan terhadap probabilitas pekerja berasal dari Divisi Pemasaran, untuk pekerja dengan pengalaman kerja kurang dari 3 tahun: `ratio_dev_to_marketing = (P_exp_dev * P_dev) / (P_exp_marketing * P_marketing)`

```
3A. Jawaban : 0.30
3B. Jawaban : 0.43
```

---
<a name='D'></a>
## **Case C**:
Sebuah perusahaan memproduksi sekrup dan melakukan inspeksi kualitas sekrup. Perusahaan tersebut menyimpan data inspeksi sekrup cacat dalam file format csv yang kita baca di bawah ini

<a name='4'></a>
### **Soal 4**: Berapa peluang sekrup cacat dari data inspeksi perusahaan tersebut <br>

<a name='5'></a>
### **Soal 5**: Berapa proporsi banyak kemasan terjual yang harus diganti oleh perusahaan?

Keterangan
- (1 = Lolos Uji Cacat, 0 = Cacat)
- Setiap kemasan berisi 10 sekrup
- Kemasan harus diganti jika terdapat satu atau lebih sekrup cacat di dalamnya.

In [ ]:
# Pastikan file .csv berada pada directory yang sama
df = pd.read_csv("./soal4_defect_test.csv")
df

id_sekrup  lolos_uji_cacat
0            1                1
1            2                1
2            3                1
3            4                1
4            5                1
..         ...              ...
495        496                0
496        497                1
497        498                1
498        499                1
499        500                1

[500 rows x 2 columns]

In [ ]:
df.head()

id_sekrup  lolos_uji_cacat
0          1                1
1          2                1
2          3                1
3          4                1
4          5                1

from matplotlib import pyplot as plt
_df_0['id_sekrup'].plot(kind='hist', bins=20, title='id_sekrup')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['id_sekrup']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'id_sekrup'}, axis=1)
              .sort_values('id_sekrup', ascending=True))
  xs = counted['id_sekrup']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('id_sekrup', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('id_sekrup')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['lolos_uji_cacat']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'lolos_uji_cacat'}, axis=1)
              .sort_values('lolos_uji_cacat', ascending=True))
  xs = counted['lolos_uji_cacat']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values('lolos_uji_cacat', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('lolos_uji_cacat')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_3['id_sekrup'].plot(kind='line', figsize=(8, 4), title='id_sekrup')
plt.gca().spines[['top', 'right']].set_visible(False)

### **Soal 4**: Berapa peluang sekrup cacat dari data inspeksi perusahaan tersebut <br>

In [ ]:
n_sekrup = df.shape[0]

n_cacat = df[df['lolos_uji_cacat'] == 0].shape[0]

Soal_4 = n_cacat / n_sekrup
print(Soal_4)

0.01


**Penjelasan Pengerjaan Soal 4** <br>

1. hitung terlebih dahulu total jumlah sekrup yang diinspeksi, yaitu `n_sekrup = df.shape[0]` dengan menggunakan properti shape dari dataframe df. Properti shape mengembalikan tuple yang berisi jumlah baris dan kolom dari dataframe, dengan indeks pertama (indeks 0) adalah jumlah baris, sehingga shape[0] akan memberikan jumlah total baris atau sekrup dalam dataframe.
2. `n_cacat = df[df['lolos_uji_cacat'] == 0].shape[0]` gunakan pengindeksan boolean untuk memfilter dataframe df berdasarkan nilai kolom `'lolos_uji_cacat'`. saya ingin mengambil baris-baris di mana nilai kolom tersebut adalah 0, yang menunjukkan sekrup cacat, lalu  menghitung jumlah baris dalam dataframe hasil filter tersebut untuk mendapatkan jumlah total sekrup cacat.
3. `Soal_4 = n_cacat / n_sekrup` selanjutnya hitung peluang antara jumlah sekrup cacat (n_cacat) dengan jumlah total sekrup (n_sekrup).

```
peluang sekrup cacat:
0.01
```

---
<a name='5'></a>
### **Soal 5**: Berapa probabilitas sebuah kemasan perlu diganti, asumsikan bahwa probabilitas sebuah sekrup cacat adalah 0.01 dan setiap kemasan berisi 10 sekrup?

Clue: $P(X>1)$ bisa dicari dengan
$$P(X>1) = 1 - P(X=0) - P(X=1)$$

In [ ]:
from scipy.stats import binom

p_cacat = 0.01  # probabilitas sekrup cacat
n_sekrup_per_kemasan = 10  # jumlah sekrup per kemasan

# probabilitas semua 10 sekrup lolos (tidak cacat)
p_semua_lolos = binom.pmf(0, n_sekrup_per_kemasan, p_cacat)

# P=probabilitas setidaknya satu sekrup cacat (kemasan perlu diganti)
p_ganti_kemasan = 1 - p_semua_lolos

Soal_5 = p_ganti_kemasan
print(Soal_5)

0.09561792499119592


**Penjelasan Pengerjaan Soal 5** <br>

1. soal ini diselesaikan menggunakan konsep distribusi binomial. Distribusi binomial digunakan untuk menghitung probabilitas mendapatkan sejumlah sukses (dalam konteks ini, sekrup cacat) dalam sejumlah percobaan independen (jumlah sekrup dalam satu kemasan), dengan probabilitas sukses tetap di setiap percobaan. Soal meminta untuk menghitung probabilitas bahwa sebuah kemasan perlu diganti, yang terjadi jika ada setidaknya satu sekrup cacat dalam kemasan. Setiap kemasan berisi 10 sekrup, dan probabilitas sekrup cacat diasumsikan 0.01.

2. dalam konteks soal ini, ada dua kemungkinan yang saling melengkapi:
(1) Semua sekrup dalam satu kemasan lolos uji kualitas (tidak ada yang cacat).
(2) Setidaknya satu sekrup dalam satu kemasan tidak lolos uji kualitas (ada yang cacat).
karena banyak kemungkinan kombinasi sekrup cacat dalam satu kemasan, saya menggunakan pendekatan menghitung probabilitas kejadian nomor 1, lalu mengurangkannya dari 1 untuk mendapatkan probabilitas kejadian nomor 2.

### Rumus Distribusi Binomial <br>
Probabilitas mendapatkan k sukses dalam n percobaan binomial diberikan oleh:
$$
P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}
$$

di mana:
- n adalah jumlah percobaan (jumlah sekrup per kemasan),
- k adalah jumlah sukses yang diinginkan (jumlah sekrup cacat),
- p adalah probabilitas sukses per percobaan (probabilitas sekrup cacat),
- $$
\binom{n}{k}
$$
adalah koefisien binomial, yang menghitung jumlah cara
k sukses dapat terjadi dalam n percobaan.

3. Hitung probabilitas setidaknya satu sekrup cacat menggunakan pendekatan probabilitas komplementer. Kita pertama kali menghitung probabilitas bahwa semua sekrup lolos inspeksi (tidak cacat), yaitu ketika k=0:

$$
P(\text{semua lolos}) = (1-p)^n
$$

probabilitas bahwa setidaknya satu sekrup cacat (kemasan perlu diganti) adalah komplementer dari probabilitas di atas:

$$
P(\text{setidaknya satu cacat}) = 1 - P(\text{semua lolos})
$$

dengan menggunakan binom.pmf dari library scipy, kita dapat langsung menghitung P(semua lolos) untuk k=0, lalu menghitung P(setidaknya satu cacat) sebagai 1-P(semua lolos).


```
probabilitas setidaknya satu sekrup cacat dalam kemasan, sehingga kemasan perlu diganti:
0.09561792499119592
```

---
<a name='6'></a>
### **Soal 6**: Sebuah kompetisi internasional mengevaluasi atlet berdasarkan dua kriteria: skor teknik dan skor artistik. Berikut ini adalah 25 total atlet yang berkompetisi. Juri memberikan penilaian untuk masing-masing atlet berdasarkan kedua kriteria tersebut. Data penilaian telah dikumpulkan sebagai berikut:

| Atlet   | Skor Teknik (X) | Skor Artistik (Y) |
|---------|-----------------|-------------------|
| Atlet 1 | 96              | 91                |
| Atlet 2 | 88              | 87                |
| Atlet 3 | 92              | 89                |
| Atlet 4 | 90              | 94                |
| Atlet 5 | 94              | 90                |
| Atlet 6 | 89              | 85                |
| Atlet 7 | 93              | 88                |
| Atlet 8 | 87              | 92                |
| Atlet 9 | 95              | 93                |
| Atlet 10| 91              | 86                |
| Atlet 11| 90              | 91                |
| Atlet 12| 92              | 88                |
| Atlet 13| 89              | 90                |
| Atlet 14| 96              | 95                |
| Atlet 15| 88              | 89                |
| Atlet 16|	92	            | 91                |
| Atlet 17|	89	            | 86                |
| Atlet 18|	87	            | 90                |
| Atlet 19|	96	            | 95                |
| Atlet 20|	88	            | 89                |


Hitung <br>
A. Untuk melihat tingkat kesulitan dari perlombaan ini, hitung nilai exspektasi untuk skor teknikal dan artistik nya <br>
B. Untuk mengetahui persebaran nilai dari masing-masing atlet, hitung nilai variance untuk kedua skor tersebut <br>
C. Hitung Covariance Matrix antara skor teknikal dengan skor artistik untuk mengetahui korelasi kedua skor tersebut<br>

**Clue**
- Hati hati dengan kata kata total, apakah itu sample? atau populasi?

In [ ]:
# Solver soal 6

# Data skor teknikal dan skor artistik
skor_teknik_x = np.array([96, 88, 92, 90, 94, 89, 93, 87, 95, 91, 90, 92, 89, 96, 88, 92, 89, 87, 96, 88])
skor_artistik_y = np.array([91, 87, 89, 94, 90, 85, 88, 92, 93, 86, 91, 88, 90, 95, 89, 91, 86, 90, 95, 89])

# A. Expectation (Nilai Harapan)
expectation_teknik = np.mean(skor_teknik_x)
expectation_artistik = np.mean(skor_artistik_y)

print("6A. Expectation:")
print("   Skor Teknik:", expectation_teknik)
print("   Skor Artistik:", expectation_artistik)

# B. Variance (Varians)
variance_teknik = np.var(skor_teknik_x, ddof=1)  # menggunakan ddof=1 karena ini sampel, bukan populasi
variance_artistik = np.var(skor_artistik_y, ddof=1)  # menggunakan ddof=1 karena ini sampel, bukan populasi

print("\n6B. Variance:")
print("   Skor Teknik:", variance_teknik)
print("   Skor Artistik:", variance_artistik)

# C. Covariance Matrix (Matriks Kovarians)
covariance_matrix = np.cov(skor_teknik_x, skor_artistik_y, ddof=1)  # menggunakan ddof=1 karena ini sampel, bukan populasi
print("\n6C. Covariance Matrix:")
print(covariance_matrix)


6A. Expectation:
   Skor Teknik: 91.1
   Skor Artistik: 89.95

6B. Variance:
   Skor Teknik: 9.46315789473684
   Skor Artistik: 8.36578947368421

6C. Covariance Matrix:
[[9.46315789 4.26842105]
 [4.26842105 8.36578947]]


**Penjelasan Pengerjaan Soal 6** <br>

1. Pertama, masukkan data skor teknikal dan artistik ke array `NumPy`. Data ini disediakan dalam bentuk list. konversi ke dalam array NumPy menggunakan `np.array()`.

2. Hitung nilai ekspektasi dari skor teknikal dan skor artistik menggunakan fungsi `np.mean()`. Hitung rata-rata dari masing-masing array skor teknikal dan skor artistik yang kemudian disimpan di variabel `expectation_teknik` dan `expectation_artistik`.

3. Hitung varians dari skor teknikal dan skor artistik menggunakan fungsi `np.var()` memakai argumen `ddof=1` karena data ini dianggap sebagai sampel, bukan populasi. Varians merupakan pengukuran sebaran data, dan nilai yang lebih tinggi menunjukkan sebaran data yang lebih besar. Varians yang lebih rendah menunjukkan sebaran data yang lebih rapat. Hasilnya disimpan dalam variabel `variance_teknik` dan `variance_artistik`.

4. Perhitungan matriks kovariansi antara skor teknikal dan skor artistik dilakukan menggunakan fungsi `np.cov()`. Seperti pada perhitungan varians, argumen `ddof=1` dipakai karena data ini dianggap sebagai sampel, bukan populasi. Matriks kovariansi memberikan informasi tentang hubungan linier antara dua variabel. Hasilnya disimpan dalam variabel `covariance_matrix`.

```
6A. Expectation:
   Skor Teknik: 91.1
   Skor Artistik: 89.95

6B. Variance:
   Skor Teknik: 9.46315789473684
   Skor Artistik: 8.36578947368421

6C. Covariance Matrix:
[[9.46315789 4.26842105]
 [4.26842105 8.36578947]]
```